# Generated by Django 4.1.7 on 2023-04-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='status',
        ),
    ]
